# Qualidade dos dados — Olist Orders

Adaptado do material `01_data_quality.ipynb` fornecido pelo professor.
O profiling usa `ydata_profiling`, já instalado no projeto. O contrato de
unicidade, completude, validade e consistência é verificado com pandas,
sem adicionar outra biblioteca de validação. Problemas reais são relatados;
os dados originais não são alterados silenciosamente.

In [1]:
import pandas as pd
from ydata_profiling import ProfileReport
from pathlib import Path

ROOT = next(p for p in (Path.cwd(), *Path.cwd().parents)
            if (p / "module_olist").is_dir())
DATA = ROOT / "data" / "raw"
REPORTS = ROOT / "reports"
REPORTS.mkdir(exist_ok=True)

/Users/ryanbernardo/Documents/Faculdade/MachineLearning/ML_projeto_SENAI/olist/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

/var/folders/92/4rgvl9cj3hv55l2d1nr5d9r80000gn/T/ipykernel_44641/2073195899.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [2]:
# carregando as orders
orders = pd.read_csv(
    DATA / "olist_orders_dataset.csv",
    parse_dates=[
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date",
    ],
)

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [3]:
# Criar um profile do dataset
profile = ProfileReport(
    orders,
    title="Data Profiling - Olist Orders",
    minimal=True,
    explorative=False
)

profile.to_file(REPORTS / "profile_olist_orders_profile.html")

# ou abrir por: profile.to_notebook_iframe()
# ou gerar html: profile.to_file("olist_orders_profile.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset:   0%|          | 0/13 [00:00<?, ?it/s, Describe variable: order_id]

Summarize dataset:   0%|          | 0/13 [00:00<?, ?it/s, Describe variable: customer_id]

Summarize dataset:   0%|          | 0/13 [00:00<?, ?it/s, Describe variable: order_estimated_delivery_date]

Summarize dataset:   0%|          | 0/13 [00:00<?, ?it/s, Describe variable: order_estimated_delivery_date]

Summarize dataset:   0%|          | 0/13 [00:00<?, ?it/s, Describe variable: order_estimated_delivery_date]

Summarize dataset:   0%|          | 0/13 [00:00<?, ?it/s, Describe variable: order_estimated_delivery_date]

Summarize dataset:   8%|▊         | 1/13 [00:00<00:01,  9.21it/s, Describe variable: order_estimated_delivery_date]

Summarize dataset:   8%|▊         | 1/13 [00:00<00:01,  6.38it/s, Describe variable: order_estimated_delivery_date]

  0%|          | 0/8 [00:00<?, ?it/s]

Summarize dataset:  15%|█▌        | 2/13 [00:00<00:03,  3.31it/s, Describe variable: order_estimated_delivery_date]

 12%|█▎        | 1/8 [00:00<00:01,  5.67it/s]

100%|██████████| 8/8 [00:00<00:00, 39.28it/s]

Summarize dataset:  62%|██████▏   | 8/13 [00:00<00:01,  3.31it/s, Get variable types]

Summarize dataset:  64%|██████▍   | 9/14 [00:00<00:01,  3.31it/s, Get dataframe statistics]

Summarize dataset:  71%|███████▏  | 10/14 [00:00<00:01,  3.31it/s, Get scatter matrix]

Summarize dataset:  71%|███████▏  | 10/14 [00:00<00:01,  3.31it/s, Take sample]

Summarize dataset:  79%|███████▊  | 11/14 [00:00<00:00,  3.31it/s, Detecting duplicates]

Summarize dataset:  86%|████████▌ | 12/14 [00:00<00:00,  3.31it/s, Get alerts]

Summarize dataset:  93%|█████████▎| 13/14 [00:00<00:00,  3.31it/s, Get reproduction details]

Summarize dataset: 100%|██████████| 14/14 [00:00<00:00,  3.31it/s, Completed]

Summarize dataset: 100%|██████████| 14/14 [00:00<00:00, 22.02it/s, Completed]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s]

Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML: 100%|██████████| 1/1 [00:00<00:00, 12.03it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file: 100%|██████████| 1/1 [00:00<00:00, 739.61it/s]

In [4]:
from IPython.display import HTML, display
display(HTML(profile.to_html()))

# Data Quality Dimensions

In [5]:
expected_status = {"created", "approved", "invoiced", "processing", "shipped",
                   "delivered", "unavailable", "canceled"}
violations = {
    "order_id ausente": orders.order_id.isna(),
    "order_id duplicado": orders.order_id.duplicated(keep=False),
    "customer_id ausente": orders.customer_id.isna(),
    "status inválido": ~orders.order_status.isin(expected_status),
    "compra sem data": orders.order_purchase_timestamp.isna(),
    "prazo prometido sem data": orders.order_estimated_delivery_date.isna(),
    "aprovação anterior à compra": orders.order_approved_at.notna()
        & orders.order_approved_at.lt(orders.order_purchase_timestamp),
}
quality_summary = pd.DataFrame({"violacoes": {rule: int(mask.sum())
                                            for rule, mask in violations.items()}})
display(quality_summary)
invalid = pd.Series(False, index=orders.index)
for mask in violations.values():
    invalid |= mask
validated_orders = orders.loc[~invalid].copy()
print(f"Linhas válidas: {len(validated_orders):,}; linhas com violações: {invalid.sum():,}")
display(orders.loc[invalid].head(10))

                             violacoes
order_id ausente                     0
order_id duplicado                   0
customer_id ausente                  0
status inválido                      0
compra sem data                      0
prazo prometido sem data             0
aprovação anterior à compra          0

Linhas válidas: 99,441; linhas com violações: 0

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [6]:
validated_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26